### PR TITLE
Add postgresql schema support

### PR DESCRIPTION
**Pull request by twkrol**
# Type of PR (feature, enhancement, bug fix, etc.)
Feature

## Description
Added '-n' for specyfing schema to backup/restore

## Why should this be added
Usefull for multitenant applications where customer's data are separated by schema, so one can backup/restore selected schema only

## Checklist

- [ ] Documentation has to be added for this feature

### CODE REVIEW

**Comment by Archmonger** [comment]
Since this appears to not be ready for review, I am marking this PR as draft. 

Please mark it as "Not Draft" when lint/tests are passing

**Comment by eriktelepovsky** [comment]
Great feature. Looking forward to it!

**Comment by twkrol** [comment]
Yeah, I want to. Just got some busy days recently.

**Comment by angryfoxx** [comment]
Hi @twkrol  @Archmonger, What is the status of this PR? Why is the status in the draft?

**Comment by twkrol** [comment]
Hey, I would love to merge this feature, but need help to make tests. Anyone?

**Comment by Archmonger** [comment]
@angryfoxx Tests are still needed for this PR.

On top of that, there's a more pressing issue that blocks all PRs from being merged #483

**Comment by angryfoxx** [comment]
Hi again @Archmonger, is that issue still persisting? I can write test and update this pr if there is no blocker.

**Comment by Archmonger** [comment]
Yes.

@johnthagen has created a workaround for our broken workflows. PRs are now mergeable again.

**Comment by johnthagen** [comment]
@angryfoxx Please resolve merge conflicts and merge `main` in your branch for CI to run properly.

**Comment by Archmonger** [comment]
Closing this in favor of #507

**Pull request closed without merging**
