### PR TITLE
Fix dbrestore on SQLite

### PR DESCRIPTION
**Pull request by Lokkook**
Adding @rgaiacs changes about restoring to sqlite db with newlines

# Bug fix

## Description

This change fix a pb when restoring fields that contains newlines.

### CODE REVIEW

**Comment by johnthagen** [comment]
Related to #254 #258

**Comment by Archmonger** [comment]
@johnthagen You mentioned something about the functional tests on this repo being iffy. Do you think that might be the reason why the `test_create_dump_with_newline` in this PR doesn't appear to run (according to codecov)?

Unrelated note, I confirmed at least one issue on Windows appears to be related to `gpg` support. See [`dbbackup/tests/utils/add_public_gpg`](https://github.com/jazzband/django-dbbackup/blob/246c1dd8cdd39f1ddb387a96e683642bd5b94709/dbbackup/tests/utils.py#L88).

**Comment by johnthagen** [comment]
> You mentioned something about the functional tests on this repo being iffy.

I don't fully recall. 

>Unrelated note, I confirmed at least one issue on Windows appears to be related to gpg support.

Maybe *nix specific tests like `gpg` could be marked as skipped on Windows: https://docs.pytest.org/en/7.1.x/how-to/skipping.html#skipping-test-functions

**Comment by Archmonger** [comment]
I'd need to confirm whether they should be skipped or not. It's very possible these tests failing is an indication that encryption support is broken on Windows.

**Comment by Archmonger** [comment]
@Lokkook @rgaiacs Are either of you interested in resolving the merge conflicts on this PR?

**Comment by rgaiacs** [comment]
I have been working with Django in the last couple of years. Sorry for not be able to resolve the conflicts.

**Comment by Lokkook** [comment]
> @Lokkook @rgaiacs Are either of you interested in resolving the merge conflicts on this PR?

Hello ! I did it. I hope I did it well :) Tell me !

**Comment by Archmonger** [comment]
This can be merged after hitting full codecov. Seems like there's two logical branches that aren't being tested.

```python
if line_str.startswith("INSERT") and not line_str.endswith(");\n"):
    sql_is_complete = False
    continue
```

```python
if not sql_is_complete and line_str.endswith(");\n"):
    sql_is_complete = True
```

**Review by Archmonger — APPROVED** [review]
This looks good, thank you for  the PR!

**Pull request merged**
