### PR TITLE
'--single-transaction' flag added to mysql backup generation command

### LINKED ISSUE #372: MySQL backup freezing on active connection
I was trying to write some *end-to-end* tests for #360 (and hence helping to complete #369). During the time I tried to generate the backup of the ***test database*** (or all databases). But, it hangs to infinity

## How Reproduce
```python
# dbbackup.tests.test_db.settings.mysql

DEBUG = False
SECRET_KEY = "it's a secret to everyone"

INSTALLED_APPS = (
    'dbbackup',
    'dbbackup.tests.testapp',
)

DATABASES = {
    "default": {
        "NAME": "cloud",
        "USER": "root",
        "PASSWORD": "password",
        "HOST": "localhost",
        "ENGINE": "django.db.backends.mysql",
        "OPTIONS": {
            "charset": "utf8mb4"
        },
    }
}

# test class
from django.test import TestCase, tag
from django.core.management import call_command
from dbbackup.tests.testapp.models import CharModel


class PopulateTestData:
    @classmethod
    def setUpTestData(cls):
        super().setUpTestData()
        for char in "QWERTY":
            CharModel.objects.create(field=char)


@tag("db_test")
class TestDBCommands(PopulateTestData, TestCase):

    def test_backup(self):
        call_command("dbbackup", "-o", "test-bkp-mysql.dump")

# test_runner.py
import os
import django

os.environ.setdefault(
    "DJANGO_SETTINGS_MODULE",
    "dbbackup.tests.test_db.settings.mysql"
)
django.setup()


if __name__ == "__main__":
    from django.test.runner import DiscoverRunner

    test_runner = DiscoverRunner(
        keepdb=False,
        interactive=False,
        verbosity=3
    )
    test_runner.run_tests([
        "dbbackup.tests.test_db.test_db_command" # path to the specific test suite
    ])
```
Then, run the suite by **`python test_runner.py`**

# Fix

Using the [***`--single-transaction`***](https://dba.stackexchange.com/a/19533/206341) flag will solve this issue.

### PR DESCRIPTION
**Pull request by jerinpetergeorge**
Fixes #372

### CODE REVIEW

**Comment by jonathan-s** [comment]
Thanks for making this. I think it would be worthwhile to write about this in the documentation that this indeed is happening. Linking to the dba post would be good to do as well.

**Comment by jerinpetergeorge** [comment]
@jonathan-s I have updated the PR with a few changes. Could you review these changes?

**Comment by jonathan-s** [comment]
Given that `--single-transaction` only works for one storage in mysql it sounds like it would make more sense for that to be False by default.

Assume that you were using a two different storage engines in mysql and you dumped both databases at the same time. If you included the flag would you get a fatal error? Or would it just ignore the flag for the engine that didn't support it?

Lastly, a question regarding ergonomics, right now you've defined it as setting. Given that this flag is something you might want to use on certain supported databases in MySQL would make more sense to put this flag on the command itself? 

Ie here -> https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/management/commands/dbbackup.py#L21-L37

**Comment by jerinpetergeorge** [comment]
> Assume that you were using a two different storage engines in mysql and you dumped both databases at the same time. If you included the flag would you get a fatal error? Or would it just ignore the flag for the engine that didn't support it?

I have done a few tests on my local machine and it seems MySQL isn't raising any error or unexpected behavior while using the `--single-transaction` flag in other engines. This leads me to believe that Mysql simply ignoring the flag if we are using it in a different, un-supported engine.

__________________

The rest of your arguments are seemed good to me, will do the necessary changes asap.

**Pull request closed without merging**
