### PR TITLE
reintroduced `inputfile.seek(0)` to utils.uncompress_file

### PR DESCRIPTION
**Pull request by truePhilipp**
## Description

This is a very small fix for #292.
I think this issue got introduced way back by #189.
In there line 244 `inputfile.seek(0)` got removed, which seems to cause this issue.
Simply reintroducing this line makes the uncompressing work again.

## Checklist

Please update this checklist as you complete each item:

-   [x] Tests have been developed for bug fixes or new functionality.
-   [x] The changelog has been updated, if necessary.
-   [x] Documentation has been updated, if necessary.
-   [x] GitHub Issues closed by this PR have been linked.

<sub>By submitting this pull request I agree that all contributions comply with this project's open source license(s).</sub>

### CODE REVIEW

**Comment by Archmonger** [comment]
Can you add a line item on the changelog, and a unit test (if feasible)?

**Comment by truePhilipp** [comment]
@Archmonger yes, sure. The changelog is docs/changelog.rst right? The newest main point is 4.0.0b0 (2021-12-19) should I just add it there?

**Comment by Archmonger** [comment]
This change would belong in an `Unreleased` section until a formal release is made.

On a side note, looks like there was a bit of forgetfulness of bumping the changelog from @johnthagen and I.

I will retroactively add `v4.0.2` and `v4.1.0` to the changelog in a separate PR.

**Comment by Archmonger** [comment]
Changelog PR has been created: https://github.com/jazzband/django-dbbackup/pull/504

**Comment by truePhilipp** [comment]
Ok, i added a test and the edited the changelog.
I have noticed that the test DbRestoreCommandTest.test_compressed does not actually check if the restore succeeded…
I don‘t know where to report that, so i‘ll just do it here. It could be fixed by adding two lines, should I do that in this merge request as well, or should i open another one for that, since it has nothing to do with this?

**Comment by Archmonger** [comment]
That's pretty minor so feel free to fold it into this PR.

**Review by Archmonger — APPROVED** [review]
This PR can be merged after resolving merge conflicts.

**Pull request merged**
