### PR TITLE
Fix dbrestore of sqlite database to like newlines

### LINKED ISSUE #254: Can't restore database if field has a line break
For SQLite, the [restore function](https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/db/sqlite.py#L66) is

~~~
    def restore_dump(self, dump):
        if not self.connection.is_usable():
            self.connection.connect()
        cursor = self.connection.cursor()
        for line in dump.readlines():
            try:
                cursor.execute(line.decode('UTF-8'))
            except OperationalError as err:
                warnings.warn("Error in db restore: {}".format(err))
            except IntegrityError as err:
                warnings.warn("Error in db restore: {}".format(err))
~~~

The function will not performer as expected if one field has a line break because the SQL instruction will be truncate.

From the issue #238 
> I get a UserWarning when running dbrestore for an sqlite database:

> UserWarning: Error in db restore: unrecognized token:
> And then a print of some text I have entered in a field. This only happens on Textfields that have line breaks. The rest of the db restore seems to work as expected.

### PR DESCRIPTION
**Pull request by rgaiacs**
Related to #238.

On Textfields that have line breaks, sqlite reports "unrecognized token"
because it doesn't keep the previous line in memory to be ammended by
the current line.

This pull requests implements a very simple logic to only send SQL
INSERT commands when the line finished with ");".

Closes #254

### CODE REVIEW

**Comment by ZuluPro** [comment]
Hi @rgaiacs 
Very great work, could you just add unit test to ensure your PR ?

**Comment by rgaiacs** [comment]
Hi @ZuluPro, could you help me with the unit test? I'm not sure if `dbbackup/tests/commands/test_dbrestore.py` is the file that I need to edit.

**Comment by ZuluPro** [comment]
Hello @rgaiacs 
There are the following things to do:
- Create a model for `TextField` in `dbbackup.tests.testapp.models.TextModel`
- Add a specific test using `TextField` in `dbbackup.tests.test_connectors. SqliteConnectorTest. test_restore_dump_with_textarea_and_newline `

Thank you very much !

**Comment by ZuluPro** [comment]
Hello @rgaiacs 
Any news ?

**Comment by rgaiacs** [comment]
> Any news ?

Still trying to write the tests. Unit tests isn't my strongest skill. :-(

**Comment by rgaiacs** [comment]
@ZuluPro I try to do as instructed but I'm receiving

~~~~
sqlite3.OperationalError: no such table: testapp_textmodel
~~~

**Comment by ZuluPro** [comment]
@rgaiacs 
Thanks for you work.
Did you do the `makemigrations` ?

**Comment by rgaiacs** [comment]
> Did you do the `makemigrations` ?

I didn't. I executed `makemigrations` and get some `UserWarning` when running the unittests. Can you have a look and provide feedback. Thanks very much for your help.

**Comment by ZuluPro** [comment]
@rgaiacs 
What is your `UserWarning` ? Is it a SQLite one ?
Could you just test the integrity of the data, if after restore `"foo\nbar"` is the same ?

**Comment by ZuluPro** [comment]
@rgaiacs Any news ?

**Comment by Lokkook** [comment]
Hi ! Is this merge request planned? Seems pretty useful 👍 
thanks!

**Comment by dtasev** [comment]
@Lokkook I wouldn't rely on it, it seems #258 has been long abandoned despite the work being there and just needing a test. Unfortunate, it seems like a great tool but if it doesn't work for the simplest cast of SQLite, it's not going anywhere near production

**Comment by ZuluPro** [comment]
@rgaiacs @Lokkook @dtasev 
The PR isn't in mergeable state.

**Comment by dtasev** [comment]
I agree, this PR is quite old so it's likely the project has moved quite a bit forward. It just seemed a shame as, at least from the comments, it sounds like it was somewhat close to being done in 2017. If people happen to come across this issue, this was my solution for SQLite in the end:

To dump the db & encrypt it:
```
manage.py dumpdata --natural-foreign --natural-primary -e contenttypes -e auth.Permission > dbdump.json
gpg --passphrase $PASSPHRASE --quiet --batch --yes -c dbdump.json && rm dbdump.json
```
To restore:
```
gpg --passphrase $PASSPHRASE --quiet --batch --yes dbdump.json.gpg
manage.py loaddata dbdump.json
```

**Comment by demonhunter3333** [comment]
it's crazy that this package doesn't even work with SQLite😢

**Comment by Archmonger** [comment]
Hey @demonhunter3333 

I took over this project not too long ago. I'm aware of several issues with the current design, and am proposing an overhaul to fix them. See the following for more info:
- https://github.com/jazzband/django-dbbackup/issues/423

**Comment by Archmonger** [comment]
Closing in favor of #383

**Pull request closed without merging**
